GigHub/Models/Gig.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GigHub.Models
{
    public class Gig
    {
        public int Id { get; set; }
        
        public ApplicationUser Artist { get; set; }
        [Required]
        public string  ArtistId {get; set;}
        public object artistid { get; internal set; }
        public DateTime DateTime { get; set; }
        [Required]
        [StringLength(225)]
        public string Venue { get; set; }
    
        public Genre Genre { get; set; }
        [Required]
        public byte GenreId { get; set; }
    }

}

GigHub/ViewModels/GigViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GigHub.Models;
using Microsoft.AspNet.Identity;

namespace GigHub.ViewModels
{
    public class GigViewModel
    {
        [Required]
        public  string Venue { get; set; }
        [Required]
        public  string Date { get; set; }
        [Required]
        public string Time { get; set; }
        [Required]
        public byte Genre { get; set; }
        public IEnumerable<Genre> Genres { get; set; }

        public DateTime GetDateTime()
        {
             return DateTime.Parse(string.Format("{ 0},{ 1}",Date,Time )); 

        }
      
        
    }
}

GigHub/Controllers/GigsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GigHub.Models;
using GigHub.ViewModels;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;

namespace GigHub.Controllers
{
    public class GigsController : Controller
    {

        private readonly ApplicationDbContext _context;

        public GigsController()
        {
            _context = new ApplicationDbContext();
        }

        [Authorize]
        public ActionResult Create()
        {
            var ViewModel = new GigViewModel
            {
                Genres = _context.Genres.ToList()

            };

            return View(ViewModel);
        }

        [Authorize]
        [HttpPost]
        public ActionResult create(GigViewModel gigviewmodel)
        {
            if (!ModelState.IsValid)
            {

                gigviewmodel.Genres = _context.Genres.ToList();
                return View("Creat", gigviewmodel);
            }
               

            var gig = new Gig
            {
                ArtistId = User.Identity.GetUserId(),
                DateTime = gigviewmodel.GetDateTime(),

                GenreId = gigviewmodel.Genre,

                Venue = gigviewmodel.Venue



            };
            _context.Gigs.Add(gig);
            _context.SaveChanges();

            return RedirectToAction("index", "home");

        }
    }
}

GigHub/Views/Gigs/Create.cshtml
@model GigHub.ViewModels.GigViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Add a Gig</h2>

@using (Html.BeginForm("Create", "Gigs"))
{
    
        <div class="form-group">
            @Html.LabelFor(m=>m.Venue)
            @Html.TextBoxFor(m=>m.Venue)
            @Html.ValidationMessageFor(m=>m.Venue)

        </div>
        <div class="form-group">
            @Html.LabelFor(m=>m.Date)
            @Html.TextBoxFor(m=>m.Date,new {@class="form-control"})
            @Html.ValidationMessageFor(m=>m.Date)
        </div>
        <div class="form-group">
            @Html.LabelFor(m=>m.Time)
            @Html.TextBoxFor(m=>m.Time,new {@class="form-control"})
            @Html.ValidationMessageFor(m=>m.Time)
        </div>
        <div class="form-group">
            @Html.LabelFor(m=>m.Genre)
            @Html.DropDownListFor(m=>m.Genre,new SelectList(Model.Genres,"Id","Name"))
            @Html.ValidationMessageFor(m=>m.Genre)
        </div>
        <div class="form-group">
            <button type="submit"  class="btn btn-primary"> Save </button>
        </div>

}